/* v4: fichas de clase. 5 etapas.
   tipo: proc (procedimiento) | comp (comprensión) | verb (habilidad verbal)
   tpl: plantilla de generador para la etapa "lo haces" */
(function(root){
"use strict";

var F = {

/* ===================== ARITMÉTICA ===================== */
ar4: {tipo:"proc", tpl:"porc_suc",
 entrada:"Un artículo de S/ 800 sube 20% y luego baja 20%. ¿Vale lo mismo que al inicio?",
 idea:"Un porcentaje no es una cantidad fija: es una parte de aquello a lo que se aplica. Si el precio cambia, el 20% ya no vale lo mismo. Por eso los porcentajes sucesivos no se suman: se multiplican.",
 herr:["Aumentar p% = multiplicar por (1 + p/100)",
   "Disminuir p% = multiplicar por (1 − p/100)",
   "Dos cambios seguidos: multiplica los dos factores",
   "Aumentar 20% y luego bajar 20% = ×1,20 × 0,80 = ×0,96, o sea 4% menos",
   "Descuentos sucesivos del 10% y 20% NO son 30%: son ×0,90 × 0,80 = ×0,72, es decir 28%"],
 patrones:["Si ves «luego», «después», «sobre el nuevo precio» → sucesivos, multiplica",
   "Si ves «del total» dos veces → son partes del mismo número, ahí sí se suman",
   "Si te preguntan la variación final, resta 1 al factor: ×0,96 → bajó 4%"],
 errores:["Sumar o restar los porcentajes (el más frecuente y el que ponen como alternativa trampa)",
   "Aplicar el segundo porcentaje al precio original en lugar del nuevo"],
 ej:[{t:"Yo lo hago", q:"S/ 500 aumenta 30% y luego disminuye 10%.",
   pasos:["Factor del aumento: 1 + 30/100 = 1,30","Factor de la disminución: 1 − 10/100 = 0,90",
     "Factor total: 1,30 × 0,90 = 1,17","Precio final: 500 × 1,17 = S/ 585","Variación: subió 17%, no 20%"]},
  {t:"Lo hacemos", q:"S/ 1200 baja 25% y luego baja 20%.",
   pasos:["Primer factor: 1 − 25/100 = ?  → 0,75","Segundo factor: 1 − 20/100 = ?  → 0,80",
     "Factor total: 0,75 × 0,80 = ?  → 0,60","Precio final: 1200 × 0,60 = ?  → S/ 720",
     "Descuento único equivalente: 40%, no 45%"]}],
 cierre:"×1,20 × 0,80 = 0,96. No vale lo mismo: quedó 4% por debajo. Bajar el mismo porcentaje que subiste nunca devuelve el precio original."},

ar5: {tipo:"proc", tpl:"regla3",
 entrada:"12 obreros hacen una obra en 20 días. ¿Cuántos días tardarán 15 obreros?",
 idea:"Todo depende de distinguir qué magnitudes son directamente proporcionales (una sube, la otra sube) e inversamente proporcionales (una sube, la otra baja). Esa decisión es el ejercicio; el cálculo es lo fácil.",
 herr:["Directas: más obra → más días; más días → más producción",
   "Inversas: más obreros → menos días; más eficiencia → menos días",
   "Método práctico: días = (obreros × días × horas × obra₂) / (obreros₂ × horas₂ × obra₁)",
   "Las magnitudes inversas van multiplicando arriba; las directas, dividiendo"],
 patrones:["Obreros, máquinas, velocidad, eficiencia → siempre inversas respecto al tiempo",
   "Cantidad de obra, dificultad, longitud → directas respecto al tiempo",
   "Verifica al final con el sentido común: si pusiste más obreros y te salieron más días, está mal"],
 errores:["Tratar obreros y días como directos","Olvidar una magnitud del enunciado (horas diarias, dificultad del terreno)"],
 ej:[{t:"Yo lo hago", q:"12 obreros, 20 días. ¿Cuántos días con 15 obreros?",
   pasos:["Obreros y días son inversos","Trabajo total = 12 × 20 = 240 obrero-días",
     "Con 15 obreros: 240 / 15 = 16 días","Comprobación: más obreros, menos días ✓"]},
  {t:"Lo hacemos", q:"8 obreros en 12 días trabajando 6 h/día. ¿Cuántos días tardan 6 obreros a 8 h/día?",
   pasos:["Trabajo total en obrero-horas: 8 × 12 × 6 = ?  → 576",
     "Obrero-horas por día del nuevo grupo: 6 × 8 = ?  → 48",
     "Días: 576 / 48 = ?  → 12 días","Menos obreros pero más horas: se compensó exactamente"]}],
 cierre:"16 días. 12 × 20 = 240 obrero-días, y 240 / 15 = 16."},

ar7: {tipo:"proc", tpl:"mcd_mcm",
 entrada:"Dos luces parpadean cada 12 y 18 segundos. Si acaban de coincidir, ¿en cuántos segundos vuelven a coincidir?",
 idea:"El MCD es el mayor número que cabe exacto en todos; el MCM es el menor en el que todos caben. Reconocer cuál te piden es casi todo el problema, porque el enunciado nunca usa esas palabras.",
 herr:["Descomposición: MCD = factores comunes con el menor exponente",
   "MCM = todos los factores, con el mayor exponente",
   "MCD(a,b) × MCM(a,b) = a × b (sirve para hallar uno si tienes el otro)",
   "Si a y b son primos entre sí: MCD = 1 y MCM = a × b"],
 patrones:["«Vuelven a coincidir», «al mismo tiempo otra vez», «menor cantidad que se reparte exacto» → MCM",
   "«Trozos iguales lo más grandes posible», «mayor número que divide», «repartir sin sobrar» → MCD",
   "Regla rápida: si el resultado debe ser mayor que los datos → MCM. Si debe ser menor → MCD"],
 errores:["Confundir MCD con MCM (ponen el otro como alternativa)","Usar el producto a × b cuando no son primos entre sí"],
 ej:[{t:"Yo lo hago", q:"MCD y MCM de 24 y 36.",
   pasos:["24 = 2³ × 3","36 = 2² × 3²","MCD: comunes con menor exponente = 2² × 3 = 12",
     "MCM: todos con mayor exponente = 2³ × 3² = 72","Verificación: 12 × 72 = 864 = 24 × 36 ✓"]},
  {t:"Lo hacemos", q:"Tres cintas de 40, 60 y 100 cm se cortan en trozos iguales lo más grandes posible.",
   pasos:["¿MCD o MCM? Trozos más grandes que dividan exacto → ?  → MCD",
     "40 = 2³×5, 60 = 2²×3×5, 100 = 2²×5²","Comunes con menor exponente: 2² × 5 = ?  → 20 cm",
     "Número de trozos: 2 + 3 + 5 = 10"]}],
 cierre:"MCM(12,18) = 36 segundos. Se pedía cuándo vuelven a coincidir, y eso siempre es MCM."},

/* ===================== ÁLGEBRA ===================== */
al3: {tipo:"proc", tpl:"prod_not",
 entrada:"Si x + 1/x = 4, halle x² + 1/x².",
 idea:"Los productos notables son atajos: resultados de multiplicaciones que aparecen tanto que conviene reconocerlos de memoria. En el examen casi nunca te piden desarrollar: te dan la suma y el producto y te piden otra combinación. Ese es el juego.",
 herr:["(a+b)² = a² + 2ab + b²","(a−b)² = a² − 2ab + b²","(a+b)(a−b) = a² − b²",
   "a² + b² = (a+b)² − 2ab","(a−b)² = (a+b)² − 4ab","a³ + b³ = (a+b)³ − 3ab(a+b)",
   "(a+b+c)² = a² + b² + c² + 2(ab + bc + ca)"],
 patrones:["Te dan a+b y ab, piden a²+b² → usa (a+b)² − 2ab",
   "Te dan a+b y ab, piden a−b → usa (a−b)² = (a+b)² − 4ab, luego raíz",
   "Aparece x + 1/x → aquí a·b = x · (1/x) = 1 siempre. Ese 1 es el regalo del problema"],
 errores:["Escribir (a+b)² = a² + b², olvidando el doble producto","Perder el signo en (a−b)²"],
 ej:[{t:"Yo lo hago", q:"Si a + b = 7 y ab = 10, halle a² + b².",
   pasos:["a² + b² = (a+b)² − 2ab","= 7² − 2(10)","= 49 − 20","= 29"]},
  {t:"Lo hacemos", q:"Si x + 1/x = 5, halle x² + 1/x².",
   pasos:["Aquí a = x, b = 1/x, entonces ab = ?  → 1",
     "x² + 1/x² = (x + 1/x)² − 2(1)","= 5² − 2 = ?  → 23"]}],
 cierre:"4² − 2 = 14. El truco: cuando ves x + 1/x, el producto vale 1."},

al5: {tipo:"proc",
 entrada:"Factorice x² + 7x + 12 y halle la suma de sus factores primos.",
 idea:"Factorizar es escribir una suma como producto. Sirve porque un producto igual a cero obliga a que un factor sea cero, y eso resuelve ecuaciones. Es la herramienta más reutilizada de todo el álgebra.",
 herr:["Factor común: ax + ay = a(x+y). Siempre se busca primero",
   "Diferencia de cuadrados: a² − b² = (a+b)(a−b)",
   "Trinomio cuadrado perfecto: a² ± 2ab + b² = (a±b)²",
   "Aspa simple: x² + bx + c = (x+m)(x+n) donde m+n = b y m·n = c",
   "Suma y diferencia de cubos: a³±b³ = (a±b)(a² ∓ ab + b²)"],
 patrones:["Dos términos y ambos cuadrados con resta → diferencia de cuadrados",
   "Tres términos empezando en x² → aspa simple: busca dos números que multiplicados den el último y sumados den el del medio",
   "Cuatro términos → agrupa de dos en dos",
   "Siempre revisa factor común antes de cualquier otra cosa"],
 errores:["Intentar aspa antes de sacar factor común","Confundir a²+b² (no factorizable en reales) con a²−b²"],
 ej:[{t:"Yo lo hago", q:"Factorice x² − 5x + 6.",
   pasos:["Busco dos números que multiplicados den 6 y sumados den −5",
     "Candidatos de 6: (1,6), (2,3) y sus negativos","−2 y −3: producto 6 ✓, suma −5 ✓",
     "x² − 5x + 6 = (x−2)(x−3)","Comprobación: x·x = x², −3x−2x = −5x, (−2)(−3)=6 ✓"]},
  {t:"Lo hacemos", q:"Factorice 3x² − 12.",
   pasos:["¿Hay factor común? → sí, 3","3x² − 12 = 3(x² − 4)",
     "x² − 4 es diferencia de cuadrados: ?  → (x+2)(x−2)","Resultado: 3(x+2)(x−2)"]}],
 cierre:"(x+3)(x+4), porque 3×4 = 12 y 3+4 = 7. La suma de los factores primos es (x+3)+(x+4) = 2x+7."},

al7: {tipo:"proc", tpl:"cuadratica",
 entrada:"En x² − 9x + 20 = 0, halle la suma y el producto de sus raíces sin resolverla.",
 idea:"Una ecuación cuadrática guarda su información en los coeficientes. Las fórmulas de Cardano-Vieta te dan la suma y el producto de las raíces directamente, sin resolver nada. En el examen eso ahorra minutos.",
 herr:["ax² + bx + c = 0","Suma de raíces = −b/a","Producto de raíces = c/a",
   "Discriminante Δ = b² − 4ac","Δ > 0: dos raíces reales distintas; Δ = 0: una doble; Δ < 0: no reales",
   "Fórmula general: x = (−b ± √Δ) / 2a"],
 patrones:["Piden suma o producto de raíces → Vieta, no resuelvas",
   "Piden «raíces iguales» o «una sola solución» → plantea Δ = 0",
   "Piden 1/x₁ + 1/x₂ → es (x₁+x₂)/(x₁x₂), o sea (−b/a)/(c/a) = −b/c",
   "Piden x₁² + x₂² → (suma)² − 2(producto). Se enlaza con productos notables"],
 errores:["Olvidar el signo negativo en −b/a","Dividir entre a solo en un término cuando a ≠ 1"],
 ej:[{t:"Yo lo hago", q:"En 2x² − 10x + 8 = 0, halle la suma y el producto.",
   pasos:["a = 2, b = −10, c = 8","Suma = −b/a = −(−10)/2 = 5","Producto = c/a = 8/2 = 4",
     "Verificación: las raíces son 1 y 4. 1+4 = 5 ✓, 1×4 = 4 ✓"]},
  {t:"Lo hacemos", q:"¿Para qué valor de k la ecuación x² + kx + 9 = 0 tiene raíz doble?",
   pasos:["Raíz doble significa Δ = ?  → 0","Δ = k² − 4(1)(9) = k² − 36",
     "k² − 36 = 0 → k = ?  → ±6","Dos respuestas válidas: k = 6 y k = −6"]}],
 cierre:"Suma = 9, producto = 20. Las raíces son 4 y 5, pero no hacía falta hallarlas."},

/* ===================== GEOMETRÍA ===================== */
ge4: {tipo:"proc", tpl:"pitagoras",
 entrada:"Una escalera de 13 m apoyada en una pared tiene su base a 5 m de ella. ¿A qué altura llega?",
 idea:"En un triángulo rectángulo, los tres lados están atados por una sola relación. Y hay ternas de números enteros que la cumplen: memorizarlas convierte muchos problemas en reconocimiento visual, sin calcular raíces.",
 herr:["a² + b² = c², donde c es la hipotenusa (siempre el lado mayor)",
   "Ternas que debes reconocer: 3-4-5, 5-12-13, 8-15-17, 7-24-25, 20-21-29, 9-40-41",
   "Los múltiplos también valen: 6-8-10, 9-12-15, 10-24-26",
   "Relaciones métricas: altura² = proyección₁ × proyección₂; cateto² = hipotenusa × su proyección"],
 patrones:["Si dos lados son de una terna conocida, el tercero sale sin calcular",
   "Escalera, poste, sombra, diagonal, distancia en L → casi siempre Pitágoras",
   "Si aparece la altura relativa a la hipotenusa → relaciones métricas, no Pitágoras directo"],
 errores:["Tomar un cateto como hipotenusa: la hipotenusa siempre es el lado mayor",
   "Sumar cuando hay que restar: si te dan la hipotenusa, se resta"],
 ej:[{t:"Yo lo hago", q:"Catetos 9 y 12. Halle la hipotenusa.",
   pasos:["¿Terna conocida? 9-12 es 3-4-5 multiplicado por 3","Entonces la hipotenusa es 5×3 = 15",
     "Verificación: 81 + 144 = 225 = 15² ✓"]},
  {t:"Lo hacemos", q:"Hipotenusa 25, un cateto 7. Halle el otro cateto.",
   pasos:["¿Terna? 7-?-25 → ?  → 7-24-25","El otro cateto es 24",
     "Comprobación: 49 + 576 = 625 = 25² ✓","Sin la terna habría que calcular √(625−49)"]}],
 cierre:"12 m. Es la terna 5-12-13: la escalera es la hipotenusa."},

ge7: {tipo:"proc", tpl:"areas",
 entrada:"Un triángulo tiene base 10 y altura 6. Otro tiene los mismos vértices salvo uno, movido en paralelo a la base. ¿Cambia el área?",
 idea:"El área mide superficie, y en casi todas las figuras planas se reduce a base por altura, con o sin dividir entre dos. Lo que se olvida es que la altura es la distancia perpendicular, no un lado cualquiera.",
 herr:["Triángulo: b·h/2","Rectángulo: b·h","Cuadrado: L²","Paralelogramo: b·h",
   "Trapecio: (B+b)·h/2","Círculo: πr²  ·  Circunferencia: 2πr",
   "Sector circular: πr²·(α/360)","Triángulo equilátero: L²√3/4","Rombo: D·d/2"],
 patrones:["Si el vértice se mueve paralelo a la base, la altura no cambia y el área tampoco",
   "Dos triángulos con la misma base y el vértice en una recta paralela tienen igual área",
   "Figuras sombreadas raras → suma y resta de figuras conocidas, no una fórmula nueva",
   "Si te piden en términos de π, no aproximes: deja el π"],
 errores:["Olvidar dividir entre 2 en el triángulo (alternativa trampa segura)",
   "Usar un lado inclinado como altura","Confundir área πr² con perímetro 2πr"],
 ej:[{t:"Yo lo hago", q:"Trapecio de bases 12 y 8, altura 5.",
   pasos:["A = (B + b)·h / 2","= (12 + 8)×5/2","= 20×5/2 = 50 u²"]},
  {t:"Lo hacemos", q:"Área sombreada: un cuadrado de lado 10 con un círculo inscrito.",
   pasos:["Área del cuadrado: 10² = ?  → 100","Radio del círculo inscrito: 10/2 = ?  → 5",
     "Área del círculo: π(5²) = ?  → 25π","Sombreado = 100 − 25π ≈ 21,5 u²"]}],
 cierre:"No cambia. Misma base, misma altura, misma área: 10×6/2 = 30."},

/* ===================== TRIGONOMETRÍA ===================== */
tr2: {tipo:"proc", tpl:"razones",
 entrada:"En un triángulo rectángulo, sen θ = 3/5. ¿Cuánto vale tan θ?",
 idea:"Las razones trigonométricas son comparaciones entre lados, no números mágicos. Con una sola razón puedes reconstruir el triángulo entero y sacar todas las demás.",
 herr:["sen = opuesto / hipotenusa","cos = adyacente / hipotenusa","tan = opuesto / adyacente",
   "csc, sec, cot son las inversas de sen, cos y tan","tan = sen / cos","sen² + cos² = 1",
   "Notables: 30°(1/2, √3/2), 45°(√2/2, √2/2), 60°(√3/2, 1/2)"],
 patrones:["Te dan una razón → dibuja el triángulo, pon los dos lados, saca el tercero con Pitágoras",
   "sen θ = 3/5 significa opuesto 3, hipotenusa 5, y entonces adyacente 4 (terna 3-4-5)",
   "Si aparece «ángulo de elevación» o «de depresión» → triángulo rectángulo con la horizontal"],
 errores:["Invertir opuesto y adyacente","Usar la hipotenusa como adyacente en la tangente"],
 ej:[{t:"Yo lo hago", q:"Si cos θ = 12/13, halle sen θ y tan θ.",
   pasos:["cos = adyacente/hipotenusa → adyacente 12, hipotenusa 13",
     "Terna 5-12-13, así que el opuesto es 5","sen = 5/13","tan = 5/12"]},
  {t:"Lo hacemos", q:"Si tan θ = 8/15, halle sen θ.",
   pasos:["tan = opuesto/adyacente → opuesto 8, adyacente 15",
     "Hipotenusa por terna 8-15-17: ?  → 17","sen = opuesto/hipotenusa = ?  → 8/17"]}],
 cierre:"tan θ = 3/4. De sen = 3/5 sale opuesto 3, hipotenusa 5 y adyacente 4."},

/* ===================== FÍSICA ===================== */
fi1: {tipo:"proc",
 entrada:"Una fórmula da una velocidad como v = a·t². ¿Puede ser correcta?",
 idea:"Toda ecuación física debe cuadrar en unidades. Esto sirve para dos cosas: descubrir fórmulas que no recuerdas y detectar errores en segundos. Es la herramienta de verificación más rápida que existe.",
 herr:["Magnitudes fundamentales: longitud L, masa M, tiempo T",
   "Velocidad: L/T   ·   Aceleración: L/T²   ·   Fuerza: MLT⁻²",
   "Trabajo y energía: ML²T⁻²   ·   Potencia: ML²T⁻³   ·   Presión: ML⁻¹T⁻²",
   "Solo se suman magnitudes de la misma dimensión",
   "Los exponentes, ángulos y logaritmos son adimensionales"],
 patrones:["Verificación rápida: reemplaza cada término por sus unidades y compara lados",
   "Si un lado da m/s y el otro m/s², la fórmula está mal, sin importar los números",
   "En alternativas con fórmulas, descarta primero las dimensionalmente imposibles"],
 errores:["Sumar magnitudes distintas","Olvidar que los coeficientes numéricos no tienen dimensión"],
 ej:[{t:"Yo lo hago", q:"¿Es válida la ecuación d = v·t + a·t²?",
   pasos:["d es L","v·t = (L/T)(T) = L ✓","a·t² = (L/T²)(T²) = L ✓",
     "Todos los términos son L: dimensionalmente válida",
     "Ojo: válida en dimensiones no significa correcta. La real lleva ½ en el último término"]},
  {t:"Lo hacemos", q:"¿Qué dimensiones tiene k en F = k·x, donde x es una longitud?",
   pasos:["F tiene dimensiones ?  → MLT⁻²","k = F/x = MLT⁻² / L = ?  → MT⁻²",
     "Eso corresponde a N/m, la constante elástica"]}],
 cierre:"No. v es L/T, pero a·t² es (L/T²)(T²) = L, una longitud. La fórmula es imposible."},

fi3: {tipo:"proc", tpl:"mruv",
 entrada:"Un auto parte del reposo y acelera 2 m/s² durante 10 s. ¿Cuánto recorre?",
 idea:"Si la velocidad no cambia, la distancia es velocidad por tiempo. Si cambia de forma constante, hay que usar la velocidad promedio, y de ahí salen todas las fórmulas del MRUV. No son cinco fórmulas nuevas: son la misma idea.",
 herr:["MRU: d = v·t","MRUV: vf = v₀ + a·t","d = v₀·t + ½a·t²","vf² = v₀² + 2a·d",
   "d = (v₀ + vf)/2 · t  (la más olvidada y a veces la más rápida)",
   "Desde el reposo, v₀ = 0 y todo se simplifica"],
 patrones:["Te dan velocidad inicial, aceleración y tiempo → d = v₀t + ½at²",
   "No te dan el tiempo pero sí las velocidades → vf² = v₀² + 2ad",
   "Frena hasta detenerse: vf = 0 y la aceleración es negativa",
   "«Parte del reposo» es un dato: v₀ = 0"],
 errores:["Olvidar el ½ en ½at² (alternativa trampa garantizada)",
   "Usar la velocidad final como si fuera constante","No poner negativa la aceleración al frenar"],
 ej:[{t:"Yo lo hago", q:"v₀ = 5 m/s, a = 3 m/s², t = 4 s. Halle la distancia.",
   pasos:["d = v₀t + ½at²","= 5(4) + ½(3)(16)","= 20 + 24","= 44 m",
     "Sin el ½ saldría 68 m: ese es el error que ponen como alternativa"]},
  {t:"Lo hacemos", q:"Un móvil a 20 m/s frena con −4 m/s² hasta parar. ¿Qué distancia recorre?",
   pasos:["Al parar, vf = ?  → 0","Uso vf² = v₀² + 2ad porque no tengo el tiempo",
     "0 = 400 + 2(−4)d","8d = 400 → d = ?  → 50 m"]}],
 cierre:"100 m. d = 0(10) + ½(2)(100) = 100 m. Desde el reposo el primer término desaparece."},

fi6: {tipo:"proc", tpl:"newton",
 entrada:"Un bloque de 5 kg es empujado con 30 N sobre una mesa con 10 N de rozamiento. ¿Qué aceleración tiene?",
 idea:"La aceleración no la produce la fuerza que aplicas, sino la fuerza neta: la suma de todas las fuerzas, con sus direcciones. Dibujar esas fuerzas antes de calcular resuelve la mitad del problema.",
 herr:["F_neta = m·a","Peso = m·g, con g ≈ 10 m/s² en el examen",
   "Normal: perpendicular a la superficie, no siempre igual al peso",
   "Rozamiento = μ·N, y se opone al movimiento",
   "En equilibrio, F_neta = 0 y la aceleración es cero"],
 patrones:["Primero dibuja todas las fuerzas, luego elige un eje positivo",
   "En el plano inclinado: componente del peso que arrastra = mg·senθ; la que aprieta = mg·cosθ",
   "Dos bloques atados: mismo módulo de aceleración para los dos",
   "«Velocidad constante» significa aceleración cero, no fuerza cero"],
 errores:["Usar la fuerza aplicada en vez de la neta","Olvidar restar el rozamiento",
   "Confundir masa con peso: la masa va en kg y no cambia con la gravedad"],
 ej:[{t:"Yo lo hago", q:"m = 4 kg, fuerza aplicada 20 N, rozamiento 4 N.",
   pasos:["F_neta = 20 − 4 = 16 N","a = F_neta/m = 16/4","a = 4 m/s²"]},
  {t:"Lo hacemos", q:"Un cuerpo de 2 kg cuelga de una cuerda que lo sube con a = 2 m/s². ¿Tensión?",
   pasos:["Fuerzas: tensión arriba, peso abajo","Peso = 2(10) = ?  → 20 N",
     "T − 20 = m·a = 2(2) = ?  → 4","T = 24 N. Al subir acelerando, la tensión supera el peso"]}],
 cierre:"4 m/s². F_neta = 30 − 10 = 20 N, y a = 20/5 = 4 m/s²."},

/* ===================== HLM ===================== */
hm5: {tipo:"proc", tpl:"trabajo",
 entrada:"A hace una obra en 6 días y B en 12. ¿En cuántos días la hacen juntos?",
 idea:"Los días no se suman ni se promedian: lo que se suma es el rendimiento, o sea la fracción de obra que cada uno hace por día. Esa es la única idea del tema.",
 herr:["Si A tarda a días, su rendimiento es 1/a de obra por día",
   "Juntos: 1/a + 1/b = 1/t","Atajo para dos: t = (a·b)/(a+b)",
   "Si uno deshace la obra (un desagüe, una fuga), su rendimiento va con signo negativo"],
 patrones:["El resultado juntos siempre es MENOR que el menor de los tiempos individuales",
   "Si te sale mayor, invertiste algo","Piscinas con llenado y desagüe → resta de rendimientos",
   "Si trabajan por turnos, calcula la obra hecha en cada tramo"],
 errores:["Sumar los días (6 + 12 = 18, que es absurdo)","Promediarlos (9 días, también imposible)"],
 ej:[{t:"Yo lo hago", q:"A en 4 días, B en 6 días. Juntos.",
   pasos:["Rendimientos: 1/4 y 1/6","Suma: 3/12 + 2/12 = 5/12 de obra por día",
     "Tiempo: 12/5 = 2,4 días","Menor que 4, el más rápido de los dos ✓"]},
  {t:"Lo hacemos", q:"Una llave llena un tanque en 3 h y un desagüe lo vacía en 6 h. Con ambos abiertos.",
   pasos:["Llave: +1/3. Desagüe: ?  → −1/6","Neto: 1/3 − 1/6 = ?  → 1/6 por hora",
     "Tiempo: ?  → 6 horas"]}],
 cierre:"4 días. 1/6 + 1/12 = 3/12 = 1/4, entonces t = 4. Y es menor que 6, como debe ser."},

/* ===================== HABILIDAD VERBAL ===================== */
hv1: {tipo:"verb",
 entrada:"En un texto de cinco párrafos sobre la contaminación del río Rímac, ¿cómo decides cuál es la idea principal sin releerlo entero?",
 idea:"La idea principal es aquello sin lo cual el texto no existiría: la afirmación que el autor quiere que aceptes. Todo lo demás son ejemplos, datos y aclaraciones que la sostienen. No es el tema (de qué habla) ni la primera oración.",
 herr:["Tema: una frase sin verbo. «La contaminación del Rímac»",
   "Idea principal: una oración completa con afirmación. «La contaminación del Rímac se debe sobre todo a la minería informal»",
   "Suele estar al inicio o al final del primer párrafo, o en la conclusión",
   "Los conectores la delatan: «por eso», «en consecuencia», «lo fundamental es», «sostenemos que»",
   "Prueba del resumen: si eliminas esa oración, ¿el texto pierde el sentido? Entonces es la principal"],
 patrones:["Lee la pregunta ANTES del texto: así sabes qué buscar",
   "Idea principal → busca la afirmación más general que englobe a las demás",
   "Alternativas trampa: una demasiado amplia (dice más de lo que el texto dice), una demasiado estrecha (es solo un detalle), una verdadera pero ajena al texto",
   "Si dos alternativas parecen correctas, elige la que cubre todo el texto, no solo un párrafo"],
 errores:["Elegir el detalle más llamativo o la cifra más impactante",
   "Elegir una afirmación que tú sabes verdadera pero que el texto no sostiene",
   "Confundir el tema con la idea principal"],
 ej:[{t:"Yo lo hago", q:"«Muchos creen que el reciclaje resuelve la crisis de residuos. Sin embargo, solo el 9% de los plásticos se recicla. El problema real es el volumen de producción, no el destino final.»",
   pasos:["Tema: la crisis de residuos plásticos","¿Qué quiere que acepte el autor? Que el reciclaje no es la solución",
     "El 9% es un dato de apoyo, no la idea","Idea principal: el problema está en la producción, no en el reciclaje",
     "Marca del texto: «el problema real es», señal explícita"]},
  {t:"Lo hacemos", q:"«La quinua fue cultivada por culturas andinas durante milenios. Fue despreciada en la Colonia como comida de indios. Hoy es un superalimento global. Su historia muestra cómo el prestigio de un alimento depende más de la política que de su valor nutritivo.»",
   pasos:["¿Cuál es el tema? →  la quinua y su valorización",
     "¿Cuál es la afirmación central? →  el prestigio alimentario depende de la política",
     "¿Dónde está? →  en la última oración","Los tres primeros datos son ?  → ejemplos que la sostienen"]}],
 cierre:"Buscas la afirmación que englobe los cinco párrafos, no la más fuerte. Lee la pregunta primero, localiza la oración que si quitas derrumba el texto, y descarta las alternativas demasiado amplias o demasiado estrechas."},

/* ===================== HUMANIDADES (molde de comprensión) ===================== */
hi3: {tipo:"comp",
 entrada:"¿Por qué la independencia del Perú fue proclamada por ejércitos venidos de afuera y no por una revolución interna?",
 idea:"La independencia peruana no fue un acto, fue un proceso de casi veinte años con protagonistas contradictorios. El examen pregunta causas y consecuencias, no solo fechas: quién impulsó qué, contra quién y con qué interés.",
 relato:"Lima era la capital del virreinato más leal a la Corona: allí estaban la burguesía comercial, el Tribunal del Consulado y la élite criolla que vivía del monopolio comercial con España. Un giro independentista amenazaba sus negocios y, tras la rebelión de Túpac Amaru II (1780-1781), también les daba miedo un levantamiento indígena que se les fuera de las manos. Por eso la iniciativa vino de los extremos del continente: San Martín desde el sur, con la Expedición Libertadora que desembarcó en Paracas en 1820 y proclamó la independencia el 28 de julio de 1821, y Bolívar desde el norte, que consumó la victoria militar en Junín y Ayacucho en 1824. La capitulación de Ayacucho cerró el dominio español en Sudamérica.",
 claves:[
   "1780-1781 · Rebelión de Túpac Amaru II: el mayor movimiento anticolonial, derrotado, y que asustó a la élite criolla",
   "1814 · Rebelión del Cusco (hermanos Angulo y Pumacahua): último gran intento interno",
   "1820 · Desembarco de San Martín en Paracas · Conferencias de Miraflores y Punchauca",
   "28 de julio de 1821 · Proclamación de la independencia en Lima",
   "1822 · Primer Congreso Constituyente · Entrevista de Guayaquil entre San Martín y Bolívar",
   "1824 · Batallas de Junín (6 de agosto) y Ayacucho (9 de diciembre) · Capitulación de Ayacucho"],
 perspectivas:[
   "Tesis de la independencia concedida: fue impuesta desde fuera por los ejércitos libertadores, sobre una élite limeña reticente (Bonilla y Spalding)",
   "Tesis de la independencia buscada: hubo un proceso interno largo de rebeliones indígenas y criollas que preparó el terreno (Macera, Flores Galindo)",
   "Lo que comparten: la independencia no cambió la estructura social; la población indígena siguió tributando y el poder quedó en manos criollas"],
 preguntas:["¿Por qué la élite limeña tenía intereses en el régimen colonial?",
   "¿Qué diferencia el proyecto de San Martín (monárquico) del de Bolívar (republicano)?",
   "¿Por qué se dice que la independencia fue política y no social?"],
 cierre:"Porque la élite criolla limeña vivía del monopolio comercial y temía una revuelta indígena como la de Túpac Amaru. La iniciativa vino del sur con San Martín y del norte con Bolívar. Y por eso la independencia cambió quién gobernaba, pero no la estructura social."}

};

root.V4 = {FICHAS:F};
})(typeof module!=="undefined"&&module.exports ? module.exports : (typeof window!=="undefined"?window:globalThis));
